spring:
  application:
    name: com-xhs-dubbo-springboot-provider
dubbo:
  scan:
    base-packages: com.xhs.dubbo.service
  protocol:
    name: dubbo
    port: 12345
  registry:
    address: zookeeper://localhost:2181
#    address: N/A